### ISSUE TITLE
Strange characters in FDIMPLES

### ISSUE THREAD

**Issue by InfoLibre** [shidel/fd-nls#1]
Hello, I'm using FreeDOS with this configuration :

In C:\FDCONFIG.SYS :
COUNTRY=033,858,C:\FDOS\BIN\COUNTRY.SYS

In C:\FDAUTO.BAT :
SET LANG=FR
...
LH DISPLAY CON=(EGA,,1)
MODE CON CODEPAGE PREPARE=((858) C:\FDOS\CPI\EGA.CPX)
MODE CON CODEPAGE SELECT=858
LH KEYB FR,858

And I've got bad characters in FDIMPLES : https://sourceforge.net/p/freedos/bugs/255/

**Comment by shidel** [comment]
Hi, thank you for moving the issue over here. On a cursory examination of a couple things, I think I may have discovered the problem. Neither the UTF-8 or the converted CP850 versions display the garbled characters you demonstrate in your other bug report. However, if you "type" the UTF-8 version in DOS it looks a lot like what you showed. So, I think there is a bug in the RBE that is causing it to use the UNICODE version instead of the DOS Codepage version when creating the multi-language listing files. The RBE (Release Build Environment) is being rewritten and the new version will not have that issue. But, it may not be done before 1.3-final. So, I will look into fixing this problem in the current version of the RBE as well. There are plans to have an RC3 release at some point and I hope to have this resolved by then.

**Comment by Petrouchka** [comment]
How FDIMPLES choose to use UTF-8 or CP850 or ? version of these files ? With LANG= or with COUNTRY= or MODE CON CODEPAGE SELECT= ?
I'm asking this question because I'm using CP858 (=CP850 with €) and not CP850.

**Comment by shidel** [comment]
Basically, UTF-8 is only being kept for two reasons. First, it is easier to edit UTF-8 in modern Windows, Linux and macOS editors. Second, the possible future use of it on the web version of the Official Software Repository. 

FDIMPLES does not care what codepage is configured on a system. It load the English metadata. Then by checking the LANG setting, it will overlay the appropriate Language file. That file needs to be compatible with he proper codepage for that language. It is a little slower, but there is a benefit of doing it by overlay. Mainly, every time a program version is updated it doe not require a whole new translation.

That is an over simplification of what FDIMPLES does when creating package information listings. For example, it index files, ism files, listing files, language files, installed package metadata and on and on and on. I haven't sat down and figured it out. But, each entry can be generated from somewhere between 3 and 20 different data points.

**Comment by Petrouchka** [comment]
Thank you for your explanations.
I was asking this question because in https://github.com/shidel/fd-nls/tree/master/packages/fr, there are 2 folders : utf-8 and cp850. They could be utf-8 and cp858, or better, utf-8 and PC-ASCII.

**Comment by shidel** [comment]
If the codepage version for french gets updated, then it probably should owe done in cp858 not cp850. And cp850 should be depreciated.

**Comment by InfoLibre** [comment]
What I wanted to say is that using cp858 or cp850 or cpxxx isn't important because these folders are still in /fr/ or another language folder. So, it would be better to use **/fr/UTF-8** and **/fr/Extended ASCII** for example, not **/fr/UTF-8** and **/fr/cpxxx**.

**Comment by shidel** [comment]
I think RC3 fixed the codepage and text issues. If they are continue to occur. Please start a new report or reopen this one. Thank you.
