### ISSUE TITLE
Turkish spelling mistakes in fdi/keyboard/BRAZIL2.KYB

### ISSUE THREAD

**Issue by cardpuncher** [shidel/fd-nls#42]
Hi Jerome,

In https://github.com/shidel/fd-nls/blob/master/fdi/keyboard/BRAZIL2.KYB I found the following line:
<code>TR=Breziya genisletilmis</code>
but it should be
<code>TR=Brezilya genişletilmiş</code>
I would submit a patch, but the file apparently uses multiple code pages and my editor can't handle that. So it's up to you :-)

PS: If there's an easy way of editing multiple code pages in a file under GNU/Linux or DOSBox, I can happily improve the wording of a couple of files in that directory. IIRC PGME could do that, but for its menus.

**Comment by shidel** [comment]
Thanks, updated it.

The multi-codepage files are a little bit of a pain to edit. As you see, most modern editors seem to like UTF and **_helpfully_** want to convert the entire document. Thereby, they mangle items in a different codepage. Fortunately, there is **_not to painful_** solution.  Use a **_stupid editor_** in **DOS**. One that just keeps whatever characters are present _as-is_. One such program is **FreeDOS Edit**.

So, your workflow could look like this... Open **DOSBox**, switch to Turkish, edit and save file, switch to French, edit and save file, done. A super simple way to accomplish this would be to use **V8Power Tools vfont** utility in a simple batch script. Something like...
```
@echo off
REM Load Turkish Font
vfont c:\somedir\cp857.v8f

REM Use FreeDOS Edit to update and save the File
edit %1 %2 %3 %4 %5 %6 %7 %8 %9

REM Reset to default system font
vfont /d
```
Since **VFONT** is not a TSR and does not use any memory, you can run that and still load/unload drivers installed before or after it changes fonts. Font's it loads do not persist across video mode changes. Unlike permanent switching through codepage settings, this utility loads them so they are only temporary. Or, you could use the font system employeed by PGME and it's suite of programs. You can load a _QFNT_ (slightly different format) with **QFNTLOAD tr857-16.fnt**, then turn it off with **QFNTLOAD reset**. PGME also includes a utility **QFNT2TSR** to turn _QFNT_ files into stand-alone permanent TSR fonts. It also has **QFNT2RAW** and **RAW2QFNT** for converting to and from it's special format. The nice thing about using PGME's system... If you don't like the font, you can easily modify it using the **EFNTDSGN** program. :-)

So, I guess an alternate version could look like...
```
@echo off
REM Load French Font
c:\pathtopgme\qfntload c:\pathtopgme\fr850-16.fnt

REM Use FreeDOS Edit to update and save the File
edit %1 %2 %3 %4 %5 %6 %7 %8 %9

REM Reset to default system font
c:\pathtopgme\qfntload reset
```
If needed, you should also be able to load and unload keyboard settings in the batch file using **MKEYB**.

Anyhow, I hope this helps. 

:-)

**Comment by cardpuncher** [comment]
Heck yes, it helped. Could you please take a look at the attached file to see if I didn't botch anything. If it's OK, I'll make some changes to other files as well.

[SWISS-FR.KYB.zip](https://github.com/shidel/fd-nls/files/6949053/SWISS-FR.KYB.zip)

**Comment by shidel** [comment]
Look fine to me. :-)

**Comment by cardpuncher** [comment]
On 7.08.2021 16:46, shidel wrote:
> Look fine to me. :-)

Thank you :-)

I think you can safely close this bug report now, I will send the files
via a PR.
